name: Build LLVM toolchain
on:
    workflow_dispatch:
        inputs:
            llvm_tag:
                required: true
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            cpu: x86_64
          - os: macos
            runner: macos-13
            cpu: x86_64
          # - os: macos
          #   runner: flyci-macos-large-latest-m1
          #   cpu: aarch64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Install Linux dependencies
      if: matrix.os == 'linux'
      run: sudo apt update && sudo apt install -yqq python3 git ninja-build cmake zstd
    - name: Install ARM toolchain
      if: matrix.os == 'linux'
      run: sudo apt install -yqq gcc-arm-linux-gnueabi g++-arm-linux-gnueabi binutils-arm-linux-gnueabi
    - name: Install AArch64 toolchain
      if: matrix.os == 'linux'
      run: sudo apt install -yqq gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - name: Install RISC-V toolchain
      if: matrix.os == 'linux'
      run: sudo apt install -yqq gcc-riscv64-linux-gnu g++-riscv64-linux-gnu binutils-riscv64-linux-gnu
    - name: Setup mold
      if: matrix.os == 'linux'
      uses: rui314/setup-mold@v1
      with:
        mold-version: 2.4.0
        make-default: false
    - name: Install macOS dependencies
      if: matrix.os == 'macos'
      run: brew install ninja zstd gnu-tar
    - name: Checkout LLVM 
      uses: actions/checkout@v4
      with:
        repository: "llvm/llvm-project"
        ref: ${{ inputs.llvm_tag }}
        path: llvm
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: toolchain
    - name: Setup Xcode
      if: matrix.os == 'macos'
      run: sudo xcode-select -s /Applications/Xcode_15.1.app
    - name: Build and install
      env:
        CXXFLAGS: -w
        CFLAGS: -w
      run: |
        mkdir build && mkdir install

        python3 ./toolchain/scripts/configure_llvm.py --build_dir=$PWD/build

        brew --prefix llvm@15

        exit

        cd build

        ninja
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-clang-tools ninja install-clangtools-distribution-stripped
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-bolt ninja install-bolttool-distribution-stripped
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-lld ninja install-lldtool-distribution-stripped
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-libcxx ninja install-stdlib-distribution-stripped
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-clang ninja install-toolchain-distribution-stripped

        ../toolchain/scripts/flatten_usr_dirs.sh $PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-clang-tools
        ../toolchain/scripts/flatten_usr_dirs.sh $PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-bolt
        ../toolchain/scripts/flatten_usr_dirs.sh $PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-lld
        ../toolchain/scripts/flatten_usr_dirs.sh $PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-libcxx
        ../toolchain/scripts/flatten_usr_dirs.sh $PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}-clang

        ninja llvm-dwp
        DESTDIR=$PWD/../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}} ninja install-pstl
        cp ./bin/llvm-dwp ../install/${{inputs.llvm_tag}}-${{matrix.os}}-${{matrix.cpu}}/bin/

        cd ../install

        tar --zstd -cf ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-clang.tar.zst ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}
        tar --zstd -cf ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-clang-tools.tar.zst ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-clang-tools
        tar --zstd -cf ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-bolt.tar.zst ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-bolt
        tar --zstd -cf ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-lld.tar.zst ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-lld
        tar --zstd -cf ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-libcxx.tar.zst ${{ inputs.llvm_tag }}-${{matrix.os}}-${{matrix.cpu}}-libcxx
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: install/${{ inputs.llvm_tag }}-${{ matrix.os }}-${{matrix.cpu}}*.tar.zst
        name: ${{matrix.os}}-${{matrix.cpu}}-toolchain

  release:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: releases_test
    - name: Checkout scripts
      uses: actions/checkout@v4
      with:
        path: scripts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Update configs
      id: update
      run: python scripts/scripts/update_llvm_configs.py --tag=${{ inputs.llvm_tag }}
    - name: Upload config
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: llvm
        commit_message: Update LLVM for ${{inputs.llvm_tag}}
        branch: releases
        create_branch: false
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        body_path: RELEASE_NOTES.txt
        tag_name: ${{ steps.update.outputs.tag_name }}
        name: LLVM Toolchain ${{ inputs.llvm_tag }}
        target_commitish: releases